routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

//Route::get('/', function () {
//    if (!Auth::user()) {
//        return view('auth.login');
//    }
//});

Route::get('/','FrontendController@index')->name('home');
Route::group(['middleware' => ['auth', 'web']], function () {
    Route::get('/dashboard', function () {
        return view('admin.dashboard');
    })->name('Home');

    Route::Resource('news', 'NewsController');
    Route::Resource('category', 'CategoryController');
    Route::Resource('albumcategory', 'AlbumCategoryController');

    Route::get('/albums', 'AlbumController@getList')->name('albums');
    Route::get('albums/createalbum', 'AlbumController@getForm')->name('create_album_form');
    Route::post('albums/createalbum', 'AlbumController@postCreate')->name('create_album');
    Route::get('/deletealbum/{id}', 'AlbumController@getDelete')->name('delete_album');
    Route::get('/albums/view-album/{id}', 'AlbumController@getAlbum')->name('show_album');
    Route::get('/albums/edit-album/{id}', 'AlbumController@editAlbum')->name('edit_album');
    Route::post('albums/edit-album', 'AlbumController@updateAlbum')->name('update_album');

    Route::get('event-category', 'EventController@categoryList');
    Route::post('insert-event-category', 'EventController@insertCategory');
    Route::delete('delete-event-category/{id}', 'EventController@deleteCategory');
    Route::get('events', 'EventController@getEventList')->name("events");
    Route::get('add-event', 'EventController@loadCreateEvent');
    Route::post('add-event', 'EventController@insertEvent');
    Route::get('/edit-event/{id}', 'EventController@editEvent')->name('edit-event');
    Route::delete('delete-event/{id}', 'EventController@deleteEvent');
});
Auth::routes([
    'register' => false]);


//Auth::routes(['register' => false]);

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\NewsCategory;
use App\Models\News;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = NewsCategory::latest()->get();
            return Datatables::of($data)
                ->addIndexColumn()
                ->editColumn('created_at', function ($row) {
                    //change over here
                    return date('d-m-Y', strtotime($row->created_at) );
                })
                ->addColumn('action', function($row){

                    $btn = ' <a href="javascript:void(0)" data-toggle="tooltip"  data-id="'.$row->id.'" data-original-title="Delete" class="btn btn-red btn-sm deleteProduct">delete</a>';

                    return $btn;
                })
                ->rawColumns(['action'])
                ->make(true);
        }


        return view('category.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->validate([
            'category'=>'required',
        ]);

        $category = new NewsCategory();
        $category->name = $request->category;
        $category->save();
        return response()->json(['success'=>'Category Added.']);

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
//        return $category;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {

//        return response()->json([
//            'data' => category
//        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
//        $request->validate([
//            'name' => 'required',
//        ]);
//        $category->name = $request->name();
//        $category->save();
//
//        return response()->json([
//            'message' => 'category updated!',
//            'success' => 'true'
//        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category s $category
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = NewsCategory::find($id)->delete();


        return response()->json(['success'=>'Category deleted successfully.']);
//        $category->delete();
//        return response()->json([
//            'message' => 'category deleted'
//        ]);
    }
}

resources/views/category/index.blade.php
@extends('layouts.app')

@section('content')
    <a href="javascript:void(0)" class="btn btn-primary mb-2" id="createNewCategory">Create Category</a>
    <div class="divide50"></div>
    <table class="table table-bordered table-striped-col data-table" width="100%">
        <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Created at</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        </tbody>
    </table>

    <div class="modal fade" id="ajaxModel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="modelHeading"></h4>
                </div>
                <div class="modal-body">
                    <form method="POST" enctype="multipart/form-data" id="uploadForm" action="javascript:void(0)">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <input type="text" name="category" placeholder="Enter Category" id="category"
                                           class="form-control">
                                </div>
                            </div>
                            <div class="col-md-12">
                                <button type="submit" class="btn btn-success" class="form-control">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script type="text/javascript">
        $(function () {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            var table = $('.data-table').DataTable({
                processing: true,
                serverSide: true,
                dataSrc: "",
                ajax: "",
                columns: [
                    {data: 'DT_RowIndex', name: 'DT_RowIndex'},
                    {data: 'name', name: 'name'},
                    {data: 'created_at', name: 'created_at'},
                    {data: 'action', name: 'action', orderable: false, searchable: false},
                ]
            });

            $('#createNewCategory').click(function () {
                $('#saveBtn').val("Add");
                $('#product_id').val('');
                $('#uploadForm').trigger("reset");
                $('#modelHeading').html("Add new category");
                $('#ajaxModel').modal('show');
            });

            $('#uploadForm').submit(function (e) {
                e.preventDefault();
                var formData = new FormData(this);
                $.ajax({
                    type: 'POST',
                    url: "{{ route('category.store') }}",
                    data: formData,
                    cache: false,
                    contentType: false,
                    processData: false,
                    success: (data) => {
                        this.reset();
                        // alert('File has been uploaded successfully');
                        // console.log(data);
                        $('#uploadForm').trigger("reset");
                        $('#ajaxModel').modal('hide');
                        table.draw();

                    },
                    error: function (data) {
                        console.log(data);
                    }
                });
            });


            $('body').on('click', '.deleteProduct', function () {

                var product_id = $(this).data("id");
                if (confirm("Are You sure want to delete !")) {

                    $.ajax({
                        type: "DELETE",
                        url: "{{ route('category.store') }}" + '/' + product_id,
                        success: function (data) {
                            table.draw();
                        },
                        error: function (data) {
                            console.log('Error:', data);
                        }
                    });
                }
            });

        });
    </script>
@endsection