routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

//Route::get('/', function () {
//    if (!Auth::user()) {
//        return view('auth.login');
//    }
//});

Route::get('/','FrontendController@index')->name('home');
Route::group(['middleware' => ['auth', 'web']], function () {
    Route::get('/dashboard', function () {
        return view('admin.dashboard');
    })->name('Home');

    Route::Resource('news', 'NewsController');
    Route::Resource('category', 'CategoryController');
    Route::Resource('albumcategory', 'AlbumCategoryController');

    Route::get('/albums', 'AlbumController@getList')->name('albums');
    Route::get('albums/createalbum', 'AlbumController@getForm')->name('create_album_form');
    Route::post('albums/createalbum', 'AlbumController@postCreate')->name('create_album');
    Route::get('/deletealbum/{id}', 'AlbumController@getDelete')->name('delete_album');
    Route::get('/albums/view-album/{id}', 'AlbumController@getAlbum')->name('show_album');
    Route::get('/albums/edit-album/{id}', 'AlbumController@editAlbum')->name('edit_album');
    Route::post('albums/edit-album', 'AlbumController@updateAlbum')->name('update_album');

    Route::get('event-category', 'EventController@categoryList');
    Route::post('insert-event-category', 'EventController@insertCategory');
    Route::delete('delete-event-category/{id}', 'EventController@deleteCategory');
    Route::get('events', 'EventController@getEventList')->name("events");
    Route::get('add-event', 'EventController@loadCreateEvent');
    Route::post('add-event', 'EventController@insertEvent');
    Route::get('/edit-event/{id}', 'EventController@editEvent')->name('edit-event');
    Route::delete('delete-event/{id}', 'EventController@deleteEvent');
});
Auth::routes([
    'register' => false]);


//Auth::routes(['register' => false]);

app/Models/Album.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\Image;

class Album extends Model
{
    public function Photos(){
        return $this->hasMany('App\Models\AlbumImagesDetail', 'albumId', 'id')->orderBy("sortIndex","asc");
    }

 }

app/Http/Controllers/AlbumController.php
<?php

namespace App\Http\Controllers;


ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

use App\Models\Album;
use App\Models\AlbumCategory;
use App\Models\AlbumImagesDetail;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Validator;
use Illuminate\Support\Facades\File;

class AlbumController extends Controller
{
    public function getList()
    {
        $albums = Album::with('Photos')->get();
        return view('albums.index', compact('albums'));
    }

    public function getAlbum($id)
    {
        $album = Album::with('Photos')->find($id);

        $albums = Album::all();
//        return View::make('album')
//            ->with('album',$album);
        return view('albums.album', compact('album', 'albums'));

    }


    public function editAlbum($id)
    {
        $album = Album::find($id);
        if ($album) {
            $images = $album->Photos;
            $categories = AlbumCategory::all();
            return view('albums.editalbum', compact('album', 'images', 'categories'));
        }
    }

    public function getForm()
    {
        $categories = AlbumCategory::all();
        return view('albums.createalbum', compact('categories'));
    }


    public function updateAlbum(Request $request)
    {
        $element_array = array(
            'name' => 'required',
            'category' => 'required'
        );
        $validator = Validator::make($request->all(), $element_array);
        if ($validator->fails()) {
            return response()->json(['errors' => $validator->errors()]);
        }
        $album = Album::find($request->id);
        if ($album) {
            $file = $request->file('cover_image');
            if ($file) {
                unlink(public_path('uploads') . '/albums/' . $album->cover_image);
                $random_name = date('YmdHis');
                $destinationPath = public_path('uploads') . '/albums/';
                $extension = $file->getClientOriginalExtension();
                $filename = $random_name . '_cover.' . $extension;
                $file->move($destinationPath, $filename);
                $album->cover_image = $filename;
            }
            $album->name = $request->name;
            $album->description = $request->description;
            $album->category = implode(',', $request->category);
            if($request->input("publishDate")) {
                $album->publishDate = Carbon::parse($request->input("publishDate"))->format("Y-m-d");
            }
            $album->save();

            $deleted_ids = $request->input("deleted_id");
            if ($deleted_ids != null) {
                $deleted_ids_array = explode(",", $deleted_ids);
                foreach (count($deleted_ids_array) > 0 ? $deleted_ids_array : array() as $d) {
                    $image_file = AlbumImagesDetail::where("id", $d)->where("albumId", $album->id)->first();
                    if ($image_file) {
                        if ($image_file->fileName != null && file_exists(public_path("uploads/albums/" . $album->id . "/" . $image_file->fileName))) {
                            unlink(public_path("uploads/albums/" . $album->id . "/" . $image_file->fileName));
                        }
                        $image_file->delete();
                    }
                }
            }
            $sort_ids = json_decode($request->input("sort_ids"), true);
            foreach (count((array)$sort_ids) > 0 ? $sort_ids : array() as $s => $value) {
                $al_file = AlbumImagesDetail::where("id", $s)->where("albumId", $album->id)->first();
                if ($al_file) {
                    $al_file->sortIndex = $value;
                    $al_file->save();
                }
            }

            $album_images = $request->file("allImageFiles");
            $image_data = $request->input("allImageData");

            if (count((array)$album_images) > 0) {
                $imgPath = public_path('uploads') . '/albums/' . $album->id . "/";
                if (!File::exists($imgPath)) {
                    File::makeDirectory($imgPath);
                }
                foreach ($album_images as $key => $value) {
                    $album_image = new AlbumImagesDetail();
                    $album_image->albumId = $album->id;
                    $image_data_array = json_decode($image_data[$key], true);
                    $album_image->sortIndex = intval($image_data_array["sortIndex"]);
                    $album_image->caption = $image_data_array["caption"];
                    $album_image->credit = $image_data_array["credit"];
                    $album_image->save();

                    $album_image->fileName = date('YmdHis') . "_" . $album->id . "_" . $album_image->id . "." . $value->getClientOriginalExtension();
                    $album_image->save();
                    $value->move($imgPath, $album_image->fileName);
                }
            }
            \Request::session()->flash('success', "Album updated successfully!");
            return response()->json(array("list" => url("albums")));
        }
    }


    public function postCreate(Request $request)
    {
        $element_array = array(
            'name' => 'required',
            'category' => 'required',
            'cover_image' => 'required|image'
        );
        $validator = Validator::make($request->all(), $element_array);
        if ($validator->fails()) {
            return response()->json(['errors' => $validator->errors()]);
        }
        $file = $request->file('cover_image');
        $random_name = date('YmdHis');
        $destinationPath = public_path('uploads') . '/albums/';
        $extension = $file->getClientOriginalExtension();
        $filename = $random_name . '_cover.' . $extension;
        $file->move($destinationPath, $filename);

        $album = new Album();
        $album->name = $request->name;
        $album->description = $request->description;
        $album->category = implode(',', $request->category);
        $album->cover_image = $filename;
        if($request->input("publishDate")) {
            $album->publishDate = Carbon::parse($request->input("publishDate"))->format("Y-m-d");
        }
        $album->save();

        $album_images = $request->file("allImageFiles");
        $image_data = $request->input("allImageData");

        if (count((array)$album_images) > 0) {
            $imgPath = public_path('uploads') . '/albums/' . $album->id . "/";
            if (!File::exists($imgPath)) {
                File::makeDirectory($imgPath);
            }
            foreach ($album_images as $key => $value) {
                $album_image = new AlbumImagesDetail();
                $album_image->albumId = $album->id;
                $image_data_array = json_decode($image_data[$key], true);
                $album_image->sortIndex = intval($image_data_array["sortIndex"]);
                $album_image->caption = $image_data_array["caption"];
                $album_image->credit = $image_data_array["credit"];
                $album_image->save();

                $album_image->fileName = date('YmdHis') . "_" . $album->id . "_" . $album_image->id . "." . $value->getClientOriginalExtension();
                $album_image->save();
                $value->move($imgPath, $album_image->fileName);
            }
        }
        \Request::session()->flash('success', "Album created successfully!");
        return response()->json(array("list" => url("albums")));
    }

    public function getDelete($id)
    {
        $album = Album::find($id);
        if ($album) {
            $albumImages = AlbumImagesDetail::where("albumId", $id)->get();
            foreach (!$albumImages->isEmpty() ? $albumImages : array() as $ai) {
                if ($ai->fileName != null && file_exists(public_path("uploads/albums/" . $album->id . "/" . $ai->fileName))) {
                    unlink(public_path("uploads/albums/" . $album->id . "/" . $ai->fileName));
                }
                $ai->delete();
            }
            unlink(public_path('uploads') . '/albums/' . $album->cover_image);
            File::deleteDirectory(public_path("uploads/albums/" . $id));
            $album->delete();
            return redirect('/albums')->with('success', 'Album Deleted!');
        }
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Album $album
     * @return \Illuminate\Http\Response
     */
    public function show(Album $album)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Album $album
     * @return \Illuminate\Http\Response
     */
    public function edit(Album $album)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Album $album
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Album $album)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Album $album
     * @return \Illuminate\Http\Response
     */
    public function destroy(Album $album)
    {
        //
    }
}

resources/views/albums/addimage.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <title>Laravel PHP Framework</title>
    <!-- Latest compiled and minified CSS -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0-rc1/css/bootstrap.min.css" rel="stylesheet">

    <!-- Latest compiled and minified JavaScript -->
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0-rc1/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container" style="text-align: center;">
    <div class="span4" style="display: inline-block;margin-top:100px;">
        @if($errors->any())
            <div class="alert alert-block alert-error fade in" id="error-block">
                <?php
                $messages = $errors->all('<li>:message</li>');
                ?>
                <button type="button" class="close" data-dismiss="alert">×</button>

                <h4>Warning!</h4>
                <ul>
                    @foreach($messages as $message)
                        {{$message}}
                    @endforeach

                </ul>
            </div>
        @endif
        <form name="addimagetoalbum" method="POST" action="{{URL::route('add_image_to_album')}}" enctype="multipart/form-data">
            @csrf
            <input type="hidden" name="album_id" value="{{$album->id}}" />
            <fieldset>
                <legend>Add an Image to {{$album->name}}</legend>
                <div class="form-group">
                    <label for="description">Image Description</label>
                    <textarea name="description" type="text"class="form-control" placeholder="Image description"></textarea>
                </div>
                <div class="form-group">
                    <label for="image">Select an Image</label>
                    <input type="file" name="image" class="form-control">
{{--                    {{Form::file('image')}}--}}
                </div>
                <button type="submit" class="btn btn-default">Add Image!</button>
            </fieldset>
        </form>
    </div>
</div> <!-- /container -->
</body>
</html>

resources/views/albums/album.blade.php
@extends('layouts.app')
@section('content')

<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <div class="album-img-container">
                <input type="file" id="imgupload" style="display:none"/>
                <a onclick="editAlbumThumbnail()" class="album-edit btn"><i class="fas fa-user-edit"></i></a>
                <img class="media-object pull-left" alt="{{$album->name}}" src="{{ asset('/uploads/albums/'.$album->cover_image) }}" width="350px">
            </div>
        </div>
        <div class="col-sm-8">
            <div class="row">
                <div class="col-sm-12">
                    <h2 class="media-heading" style="font-size: 26px;">Album Name:</h2>
                    <p>{{$album->name}}</p>
                </div>
                <div class="col-sm-12">
                    <h2 class="media-heading" style="font-size: 26px;">Album Description :</h2>
                    <p>{{$album->description}}<p>
                </div>
                <div class="col-sm-12">
                    <a href="{{URL::route('add_image',array('id'=>$album->id))}}"><button type="button"class="btn btn-primary btn-large">Add New Image to Album</button></a>
                    <a href="{{URL::route('delete_album',array('id'=>$album->id))}}" onclick="return confirm('Are yousure?')"><button type="button"class="btn btn-danger btn-large">Delete Album</button></a>
                </div>
            </div>
        </div>
    </div>

    <div class="row pt-5">
        @foreach($album->Photos as $photo)
            <div class="col-lg-3">
                <div class="thumbnail" style="max-height: 350px;min-height: 350px;">
                    <img alt="{{$album->name}}" src="{{ asset('/uploads/albums/'.$photo->image) }}">
                    <div class="caption">
                        <p>{{$photo->description}}</p>
                        <p>Created date:  {{ date("d F Y",strtotime($photo->created_at)) }}at {{ date("g:ha",strtotime($photo->created_at)) }}</p>
                        <a href="{{URL::route('delete_image',array('id'=>$photo->id))}}" onclick="returnconfirm('Are you sure?')"><button type="button" class="btn btn-danger btn-small">Delete Image</button></a>
                        <p>Move image to another Album :</p>
                        <form name="movephoto" method="POST" action="{{URL::route('move_image')}}" enctype="multipart/form-data">
                            @csrf
                            <select name="new_album">
                                @foreach($albums as $others)
                                    <option value="{{$others->id}}">{{$others->name}}</option>
                                @endforeach
                            </select>
                            <input type="hidden" name="photo" value="{{$photo->id}}" />
                            <button type="submit" class="btn btn-small btn-info" onclick="return confirm('Are you sure?')">Move Image</button>
                        </form>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
</div>
@endsection

resources/views/albums/albumscat.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12">
                <a href="javascript:void(0)" class="btn btn-primary mb-2" id="createNewCategory">Create Gallery Category</a>
                <br>
                <table class="table table-bordered table-striped-col data-table" width="100%">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Created at</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div class="modal fade" id="ajaxModel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="modelHeading"></h4>
                </div>
                <div class="modal-body">
                    <form method="POST" enctype="multipart/form-data" id="uploadForm" action="javascript:void(0)" >
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <input type="text" name="category" placeholder="Enter Category" id="category" class="form-control">
                                </div>
                            </div>
                            <div class="col-md-12">
                                <button type="submit" class="btn btn-success" class="form-control">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(function () {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            var table = $('.data-table').DataTable({
                processing: true,
                serverSide: true,
                dataSrc: "",
                ajax: "",
                columns: [
                    {data: 'DT_RowIndex', name: 'DT_RowIndex'},
                    {data: 'name', name: 'name'},
                    {data:'created_at', name: 'created_at'},
                    {data: 'action', name: 'action', orderable: false, searchable: false},
                ]
            });

            $('#createNewCategory').click(function () {
                $('#saveBtn').val("Add");
                $('#product_id').val('');
                $('#uploadForm').trigger("reset");
                $('#modelHeading').html("Add New Image");
                $('#ajaxModel').modal('show');
            });

            $('#uploadForm').submit(function(e) {
                e.preventDefault();
                var formData = new FormData(this);
                $.ajax({
                    type: 'POST',
                    url: "{{ route('albumcategory.store') }}",
                    data: formData,
                    cache: false,
                    contentType: false,
                    processData: false,
                    success: (data) => {
                        this.reset();
                        // alert('File has been uploaded successfully');
                        // console.log(data);
                        $('#uploadForm').trigger("reset");
                        $('#ajaxModel').modal('hide');
                        table.draw();

                    },
                    error: function (data) {
                        console.log(data);
                    }
                });
            });


            $('body').on('click', '.deleteProduct', function () {

                var product_id = $(this).data("id");
                confirm("Are You sure want to delete !");

                $.ajax({
                    type: "DELETE",
                    url: "{{ route('albumcategory.store') }}"+'/'+product_id,
                    success: function (data) {
                        table.draw();
                    },
                    error: function (data) {
                        console.log('Error:', data);
                    }
                });
            });

        });
    </script>
@endsection

resources/views/albums/createalbum.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Create Gallery') }}</div>


                    <div class="card-body">
                        @if($errors->count())
                            <div class="alert alert-success" role="alert">
                                <?php
                                $messages = $errors->all('<li>:message</li>');
                                ?>
                                <button type="button" class="close" data-dismiss="alert">×</button>

                                <h4>Warning!</h4>
                                <ul>
                                    @foreach($messages as $message)
                                        {{$message}}
                                    @endforeach

                                </ul>
                            </div>
                        @endif


                        <form id="createnewalbum" name="createnewalbum" method="POST"
                              action="{{URL::route('create_album')}}"
                              enctype="multipart/form-data">
                            @csrf
                            <div class="form-group">
                                <label for="name">Album Name</label>
                                <input name="name" type="text" class="form-control" placeholder="Album Name" value="">
                                <label class="text-danger" for="name"></label>
                            </div>
                            <div class="form-group">
                                <label for="description">Album Description</label>
                                <textarea name="description" type="text" class="form-control"
                                          placeholder="Album description" cols="30" rows="10"></textarea>
                            </div>
                            <div class="form-group">
                                <label for="">Publish At</label>
                                <input type="date" name="publishDate" class="form-control">
                            </div>
                            <label for="">Select Gallery Category</label>

                            <div class="form-group form-inline">
                                @foreach($categories as $cat)
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="checkbox" name="category[]"
                                               value="{{ $cat->id }}">
                                        <label class="form-check-label" for="Checkbox">{{ $cat->name }}</label>
                                    </div>
                                @endforeach
                            </div>
                            <label class="text-danger" for="category"></label>
                            <div class="form-group">
                                <label for="cover_image">Select a Cover Image</label>
                                <input type="file" name="cover_image" id="cover_image" class="form-control">
                                <label class="text-danger" for="cover_image"></label>
                            </div>
                            <div class="form-group">
                                <button type="button" class="btn btn-secondary" data-toggle="modal"
                                        data-target="#imageUploadModal">
                                    Upload image(s)
                                </button>
                            </div>
                            <button type="button" class="btn btn-primary" onclick="javascript:submitGallery()">Create
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- /container -->

    <!-- Modal -->
    @include("albums/imageModal")
@endsection
{{--</body>--}}
{{--</html>--}}

resources/views/albums/editalbum.blade.php
@extends('layouts.app')
@section('content')
    <form name="editalbum" id="editalbum" method="POST" action="{{URL::route('update_album')}}"
          enctype="multipart/form-data">
        @csrf
        <div class="container">
            <div class="row">
                <div class="col-sm-8">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label for="name">Album Name</label>
                                <input name="name" type="text" class="form-control" placeholder="Album Name"
                                       value="{{$album->name}}">
                                <label class="text-danger" for="name"></label>
                            </div>
                            <div class="form-group">
                                <label for="description">Album Description</label>
                                <textarea name="description" type="text" class="form-control"
                                          placeholder="Album description" cols="30"
                                          rows="10">{{$album->description}}</textarea>
                            </div>
                            <div class="form-group">
                                <label for="">Publish At</label>
                                <input type="date" name="publishDate" class="form-control" @if($album->publishDate != "")value="{{ date('Y-m-d', strtotime($album->publishDate)) }}" @endif>
                            </div>
                            <label for="">Select Gallery Category</label>

                            <div class="form-group form-inline">
                                @php
                                    $category = explode(",","$album->category")
                                @endphp
                                @foreach($categories as $cat)
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="checkbox" name="category[]"
                                               value="{{ $cat->id }}" <?=(in_array($cat->id, $category)) ? "checked" : " ";?>>
                                        <label class="form-check-label" for="Checkbox">{{ $cat->name }}</label>
                                    </div>
                                @endforeach
                            </div>
                            <label class="text-danger" for="category"></label>
                            <input type="hidden" name="id" id="album_id" value="{{$album->id}}">

                        </div>
                        <div class="col-sm-12">
                            <button type="button" class="btn btn-primary btn-large" data-toggle="modal"
                                    data-target="#imageUploadModal">Add New Image to Album
                            </button>
                            <a href="{{URL::route('delete_album',array('id'=>$album->id))}}"
                               onclick="return confirm('Are yousure?')">
                                <button type="button" class="btn btn-danger btn-large">Delete Album</button>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="album-img-container">
                        <input type="file" name="cover_image" id="imgupload" style="display:none"
                               onchange="readURL(this)"/>
                        <a onclick="editAlbumThumbnail()" class="album-edit btn"><i class="fas fa-user-edit"></i></a>
                        <img class="media-object pull-left" alt="{{$album->name}}"
                             src="{{ asset('/uploads/albums/'.$album->cover_image) }}" width="350px">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12 mt-5">
                    <button type="button" class="btn btn-primary" onclick="javascript:submitGallery()">Submit</button>
                </div>
            </div>
        </div>
    </form>
    @include("albums/imageModal",["images" => $images])
@endsection